### ISSUE TITLE
Password Secrets

### ISSUE THREAD

**Issue by ghost** [evyatar9/Writeups#2]
Is there any reason you made (at least one) pdf file that is password protected?

**Comment by evyatar9** [comment]
Hi @zach83,
Sure,
If you want to see writeups for HackTheBox active machines - you must enter the machine root hash as a PDF password.

**Comment by ghost** [comment]
Okay...
I'm guessing by that you mean the flag?

**Comment by evyatar9** [comment]
I mean the root hash from ```/etc/shadow```, Example:

```console
>cat /etc/shadow
root:$6$LCKz7Uz/FuAAAJ6o$LaOqabtpLJIhOzr7YwJzFPX4Nd**********k4S1.CY7D/ECYVfP4Q5eS43/PMtsOa5up1ThgjB3.xUZsHyH*1:18754:0:99999:7:::
```

At this case The password will be 
```console
$6$LCKz7Uz/FuAAAJ6o$LaOqabtpLJIhOzr7YwJzFPX4Nd**********k4S1.CY7D/ECYVfP4Q5eS43/PMtsOa5up1ThgjB3.xUZsHyH*1
```

Btw, you get get it simply by:
```console
>cat /etc/shadow | grep root | cut -d':' -f2
$6$LCKz7Uz/FuAAAJ6o$LaOqabtpLJIhOzr7YwJzFPX4Nd**********k4S1.CY7D/ECYVfP4Q5eS43/PMtsOa5up1ThgjB3.xUZsHyH*1
```
